---
image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - DEPLOYMENT_NAME={{DEPLOYMENT_NAME}}
  - GINKGO_PARALLEL={{GINKGO_PARALLEL}}

script:
  - ./scripts/run_integration_tests
